diagnosisapplication/diagnosis/urls.py
from django.urls import path
from . import views

app_name = 'diagnosis'

urlpatterns = [
    path('', views.diagnosis_list, name="diagnosis-list"),
    path('symp/', views.symptoms_list, name="symptom-list"),
    path('new-diagnosis/', views.create_diagnosis, name="create-diagnosis"),
    path('new-symptom/', views.create_symptom, name="create-symptom"),
    path('symptom-history/', views.symptom_history, name='symptom_history'),
    path('diagnosis-history/', views.diagnosis_history, name='diagnosis_history'),
    path('update/symp/<int:symptom_id>/', views.update_symptom, name='update_symptom'),
    path('delete/symp/<int:symptom_id>/', views.delete_symptom, name='delete_symptom'),
    path('update/<int:diagnosis_id>/', views.update_diagnosis, name='update_diagnosis'),
    path('delete/<int:diagnosis_id>/', views.delete_diagnosis, name='delete_diagnosis'),
    path('symp/<slug:slug>', views.symptom_page, name="symptom-page"),
    path('<slug:slug>', views.diagnosis_page, name="diagnosis-page"),

    # API
    path('api/symp/', views.SymptomListCreate.as_view(), name="symptom-view-create"),
    path('api/symp/<int:pk>/', views.SymptomRetrieveUpdateDestroy.as_view(), name="symptom-update"),
    path('api/diagnosis/', views.DiagnosisListCreate.as_view(), name="diagnosis-view-create"),
    path('api/diagnosis/<int:pk>/', views.DiagnosisRetrieveUpdateDestroy.as_view(), name="diagnosis-update"),
]

diagnosisapplication/diagnosisapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.views.static import serve
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('diagnosis/', include('diagnosis.urls')),
    path('users/', include('users.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/docs/', SpectacularSwaggerView.as_view(url_name="schema"))
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diagnosisapplication/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_user, name="register"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

diagnosisapplication/templates/index.html
{% extends "layout.html" %} 

{% block title %}Home{% endblock title %} 


{% block content %}
<h2>HomePage</h2>

{% endblock content %}

diagnosisapplication/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %} Django App {% endblock title %}</title>
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">DiagnosisApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'diagnosis:symptom-list' %}">Symptoms</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'diagnosis:diagnosis-list' %}">Diagnoses</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                User
              </a>
              {% if user.is_authenticated %}
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'diagnosis:create-symptom' %}">Create Symptom</a></li>
                <li><a class="dropdown-item" href="{% url 'diagnosis:create-diagnosis' %}">Create Diagnosis</a></li>
                <li><a class="dropdown-item" href="{% url 'diagnosis:symptom_history' %}">Symptom History</a></li>
                <li><a class="dropdown-item" href="{% url 'diagnosis:diagnosis_history' %}">Diagnosis History</a></li>
                <li>
                    <form class="logout" action="{% url 'users:logout' %}" method="post">
                      {% csrf_token %}
                      <button class="dropdown-item" style="cursor: pointer;">Logout</button>
                    </form>
                </li>
              </ul>
              {% else %}
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'users:register' %}">Register</a></li>
                <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a></li>
              </ul>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %} {% endblock content %}
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</html>